# Default values for ekoparty-flask-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: default

image:
  repository: tty0/flask_app
  pullPolicy: Always
  tag: "1.1"

service:
  type: ClusterIP
  port: 8000

limits:
  cpu: 0.2
  memory: 128Mi
requests:
  cpu: 0.4
  memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  hostname: "hello-world.tty0.guru"
  class: "nginx"
  path: "/"
  dnsController:
    enabled: true
    hostname: tty0.guru
    ttl: 120
  certManager:
    enabled: true
    issuer: "letsencrypt-prod"
    acmeChallenge: "http01"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, HEAD"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/default-backend: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"

conf:
  salute: "Control Is An Illusion"
  header: "https://heraldodemexico.com.mx/u/fotografias/m/2021/5/12/f960x540-369933_444008_0.jpg"

